### ISSUE TITLE
phenio has redundant is-a links:

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/phenio#90] opened 2024-11-15 23:50 UTC
https://monarchinitiative.org/GO:0006915#hierarchy

This is flattening everything here

 * Thing
    * [i] BFO:0000015 ! process
        * [i] GO:0008150 ! biological_process
            * [i] GO:0009987 ! cellular process
                * [i] GO:0008219 ! cell death
                    * [i] GO:0012501 ! programmed cell death
                        * [i] **GO:0006915 ! apoptotic process**
                            * [i] GO:1990009 ! retinal cell apoptotic process
                                * [i] GO:1990010 ! compound eye retinal cell apoptotic process
                                * [i] GO:0097474 ! retinal cone cell apoptotic process
                                * [i] GO:0097473 ! retinal rod cell apoptotic process
                            * [i] GO:1904606 ! fat cell apoptotic process
                            * [i] GO:1904516 ! myofibroblast cell apoptotic process
                            * [i] GO:1904019 ! epithelial cell apoptotic process
                                * [i] GO:1990134 ! epithelial cell apoptotic process involved in palatal shelf morphogenesis
                                * [i] GO:1990086 ! lens fiber cell apoptotic process
                                * [i] GO:1904700 ! granulosa cell apoptotic process
                                * [i] GO:1903210 ! podocyte apoptotic process
                                * [i] GO:1902488 ! cholangiocyte apoptotic process
                                * [i] GO:1902484 ! Sertoli cell apoptotic process
                                * [i] GO:0097284 ! hepatocyte apoptotic process
                                * [i] GO:0097283 ! keratinocyte apoptotic process
                                * [i] GO:0097050 ! type B pancreatic cell apoptotic process
                            * [i] GO:1902742 ! apoptotic process involved in development
                                * [i] GO:1900205 ! apoptotic process involved in metanephric nephron tubule development
                                * [i] GO:1900204 ! apoptotic process involved in metanephric collecting duct development
                                * [i] GO:1900200 ! mesenchymal cell apoptotic process involved in metanephros development
                                    * [i] GO:1901147 ! mesenchymal cell apoptotic process involved in metanephric nephron morphogenesis
                                * [i] GO:0061364 ! apoptotic process involved in luteolysis
                                * [i] GO:0060561 ! apoptotic process involved in morphogenesis
                                    * [i] GO:1990134 ! epithelial cell apoptotic process involved in palatal shelf morphogenesis
                                    * [i] GO:1902263 ! apoptotic process involved in embryonic digit morphogenesis
                                    * [i] GO:1902262 ! apoptotic process involved in blood vessel morphogenesis
                                    * [i] GO:1901145 ! mesenchymal cell apoptotic process involved in nephron morphogenesis
                                        * [i] GO:1901147 ! mesenchymal cell apoptotic process involved in metanephric nephron morphogenesis
                                        * [i] GO:1901146 ! mesenchymal cell apoptotic process involved in mesonephric nephron morphogenesis
                                    * [i] GO:0060885 ! clearance of cells from fusion plate by apoptotic process
                                    * [i] GO:0060609 ! apoptotic process involved in tube lumen cavitation
                                        * [i] GO:0060663 ! apoptotic process involved in salivary gland cavitation
                                    * [i] GO:0060057 ! apoptotic process involved in mammary gland involution
                                    * [i] GO:0003278 ! apoptotic process involved in heart morphogenesis
                                        * [i] GO:0003296 ! apoptotic process involved in atrial ventricular junction remodeling
                                        * [i] GO:0003277 ! apoptotic process involved in endocardial cushion morphogenesis
                                        * [i] GO:0003276 ! apoptotic process involved in heart valve morphogenesis
                                        * [i] GO:0003275 ! apoptotic process involved in outflow tract morphogenesis
                                * [i] GO:0045476 ! nurse cell apoptotic process
                                * [i] GO:0002516 ! B cell deletion
                                    * [i] GO:0002454 ! peripheral B cell deletion
                                    * [i] GO:0002342 ! central B cell deletion
                            * [i] GO:1902489 ! hepatoblast apoptotic process
                            * [i] GO:1902362 ! melanocyte apoptotic process
                            * [i] GO:0140208 ! apoptotic process in response to mitochondrial fragmentation
                            * [i] GO:0097152 ! mesenchymal cell apoptotic process
                                * [i] GO:1901145 ! mesenchymal cell apoptotic process involved in nephron morphogenesis
                                    * [i] GO:1901147 ! mesenchymal cell apoptotic process involved in metanephric nephron morphogenesis
                                    * [i] GO:1901146 ! mesenchymal cell apoptotic process involved in mesonephric nephron morphogenesis
                                * [i] GO:1900200 ! mesenchymal cell apoptotic process involved in metanephros development
                                    * [i] GO:1901147 ! mesenchymal cell apoptotic process involved in metanephric nephron morphogenesis
                            * [i] GO:0072577 ! endothelial cell apoptotic process
                            * [i] GO:0071887 ! leukocyte apoptotic process
                                * [i] GO:0097048 ! dendritic cell apoptotic process
                                * [i] GO:0071888 ! macrophage apoptotic process
                                * [i] GO:0070227 ! lymphocyte apoptotic process
                                    * [i] GO:0070246 ! natural killer cell apoptotic process
                                    * [i] GO:0070231 ! T cell apoptotic process
                                        * [i] GO:1905398 ! activated CD4-positive, alpha-beta T cell apoptotic process
                                        * [i] GO:1905397 ! activated CD8-positive, alpha-beta T cell apoptotic process
                                        * [i] GO:1902482 ! regulatory T cell apoptotic process
                                        * [i] GO:0070242 ! thymocyte apoptotic process
                                        * [i] GO:0070238 ! activated T cell autonomous cell death
                                        * [i] GO:0006924 ! activation-induced cell death of T cells
                                    * [i] GO:0001783 ! B cell apoptotic process
                                        * [i] GO:0071948 ! activation-induced B cell apoptotic process
                                        * [i] GO:0002901 ! mature B cell apoptotic process
                                        * [i] GO:0002516 ! B cell deletion
                                            * [i] GO:0002454 ! peripheral B cell deletion
                                            * [i] GO:0002342 ! central B cell deletion
                                * [i] GO:0033024 ! mast cell apoptotic process
                                * [i] GO:0001781 ! neutrophil apoptotic process
                            * [i] GO:0071839 ! apoptotic process in bone marrow cell
                            * [i] GO:0051402 ! neuron apoptotic process
                                * [i] GO:1905584 ! outer hair cell apoptotic process
                                * [i] GO:0110088 ! hippocampal neuron apoptotic process
                                * [i] GO:0097474 ! retinal cone cell apoptotic process
                                * [i] GO:0097473 ! retinal rod cell apoptotic process
                                * [i] GO:0097049 ! motor neuron apoptotic process
                            * [i] GO:0044346 ! fibroblast apoptotic process
                            * [i] GO:0043276 ! anoikis
                            * [i] GO:0034349 ! glial cell apoptotic process
                                * [i] GO:0097252 ! oligodendrocyte apoptotic process
                            * [i] GO:0033028 ! myeloid cell apoptotic process
                                * [i] GO:1902217 ! erythrocyte apoptotic process
                                * [i] GO:0071888 ! macrophage apoptotic process
                                * [i] GO:0033024 ! mast cell apoptotic process
                                * [i] GO:0001781 ! neutrophil apoptotic process
                            * [i] GO:0010657 ! muscle cell apoptotic process
                                * [i] GO:0034390 ! smooth muscle cell apoptotic process
                                    * [i] GO:1905288 ! vascular associated smooth muscle cell apoptotic process
                                * [i] GO:0010658 ! striated muscle cell apoptotic process
                                    * [i] GO:0010659 ! cardiac muscle cell apoptotic process
                            * [i] GO:0006925 ! inflammatory cell apoptotic process
                                * [i] GO:0071888 ! macrophage apoptotic process
                                * [i] GO:0001781 ! neutrophil apoptotic process

**Comment by cmungall** [comment] 2024-11-15 23:50
phenio:

```
sqlite> select count(*) from statements where object='GO:0006915' and predicate='rdfs:subClassOf';
66
```

go:

```
sqlite> select count(*) from statements where object='GO:0006915' and predicate='rdfs:subClassOf';
19

```

**Comment by cmungall** [comment] 2024-11-15 23:51
Likely over-eager relax.

**Comment by matentzn** [comment] 2024-11-16 14:54
There are two ways two solve this (I tried both, they work fine):

1. Drop the relax, and trust that all ontologies that are part of PHENIO run relax at release time (most use ODK, so they do)
2. Add a reduce step right after the relax step (which introduces the need to run the reasoner, but is more rigorous in case an imported ontology does not `relax` their release.

I think we don't need to run relax. In the interest of making application ontologies a pure plug and play experience as we have set out to do according to our vision, we should make sure our component ontologies are in shape for modular ontology development. see #92

**Comment by caufieldjh** [comment] 2024-11-17 20:30
Will close once confirmed fixed in new build

**Comment by caufieldjh** [comment] 2024-11-18 16:57
OK, now seeing the same number as GO itself with a fresh `phenio.db` built with the most recent phenio build:
```
sqlite> .open "phenio.db"
sqlite> select count(*) from statements where object='GO:0006915' and predicate='rdfs:subClassOf';
19
```

So I will consider this solved.

**Closed as completed by caufieldjh** 2024-11-18 16:57 UTC
